plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.voobrazimoe.pinballfantasies'
    compileSdk 36
    ndkVersion '28.2.13676358'

    defaultConfig {
        applicationId 'io.github.voobrazimoe.pinballfantasies'
        minSdk 27
        targetSdk 36
        versionCode 1
        versionName '0.0.0-a1'

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    buildFeatures {
        prefab true
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.games:games-activity:4.4.2'
}
